import { github, portfolio } from './layout.mjs';
import { abilitySelector } from './ability-selector.mjs';
const repo = `${github}/jamiewilliams.website`;
const game = `${github}/Jamie-Hackathon-2026`;
const play = 'https://play.unity.com/en/games/51c4cc8b-b2fc-4f07-a06d-968e66fd5fc3/polished';
const heading = (index, title, text) => `<header class="page-heading"><span class="eyebrow">${index}</span><h1>${title}</h1><p>${text}</p></header>`;
const article = (contents, body) => `<div class="article-layout"><aside class="article-index"><span class="eyebrow">ON THIS PAGE</span><nav aria-label="On this page">${contents.map(([id, title])=>`<a href="#${id}">${title}</a>`).join('')}</nav></aside><article class="prose">${body}</article></div>`;
export const detailPages = [
{path:'/lab/',title:'Projects',description:'Jamie Williams’s RFID platformer and links to more game-development projects.',body:
 heading('PROJECTS', 'Projects.', 'Games and code I’ve worked on.') +
 `<a class="experiment-row" href="/lab/rfid/"><span class="experiment-id">UNITY / C#</span><div><h2>RFID platformer</h2><p>A hackathon game with physical tokens for switching abilities. It also works with a keyboard.</p></div><div class="experiment-meta"><span>ESP32 / RFID</span><span>Solo project</span></div><span class="row-arrow" aria-hidden="true">↗</span></a><p class="archive-footnote">More of my work is on <a href="${portfolio}">my game dev portfolio ↗</a> and <a href="${github}">GitHub ↗</a>.</p>`},
{path:'/lab/rfid/',title:'RFID platformer',description:'A Unity platformer Jamie Williams made for a hackathon, with an ESP32 RFID controller.',body:
 heading('UNITY / C# / ESP32', 'RFID platformer', 'I made this for a hackathon. Scanning a physical token changes which ability you can use in the game.') +
 `<div class="project-facts"><div><span class="eyebrow">PROJECT</span><strong>Solo hackathon build</strong></div><div><span class="eyebrow">FIRST VERSION</span><strong>2–3 days</strong></div><div><a class="text-link" href="${play}">Play in your browser ↗</a></div></div>${abilitySelector()}` +
 article([['game','The game'],['controller','The controller'],['rough','What’s unfinished'],['links','Links']], `<section id="game"><h2>The game</h2><p>It’s a 2D speedrun platformer with four abilities: dash, wall jump, gravity flip, and time stop. You can switch between them using RFID tokens or a regular keyboard.</p><p>The movement has acceleration, coyote time, jump buffering, and variable jump height. There’s also a timer, a local leaderboard, and a ghost replay.</p></section><section id="controller"><h2>The controller</h2><p>An MFRC522 reader scans the tokens. The ESP32 sends a number key over Bluetooth, and Unity uses that key to select an ability.</p><div class="signal-flow" aria-label="Controller input path"><span>RFID token</span><b aria-hidden="true">↓</b><span>MFRC522 reader + ESP32</span><b aria-hidden="true">↓</b><span>Bluetooth keyboard input</span><b aria-hidden="true">↓</b><span>Unity</span></div><p>The ESP32 acts as a keyboard, so the game doesn’t need a separate input system for the hardware.</p></section><section id="rough"><h2>What’s unfinished</h2><p>Crush detection, resets, and some race and leaderboard edge cases still need work. The repository has more recent changes than some of the exported builds; the README has the development notes and known issues.</p></section><section id="links"><h2>Try it</h2><p><a href="${play}">Play the browser build ↗</a></p><p><a href="${game}">Source code and dev notes ↗</a></p></section>`)},
{path:'/about/',title:'About',description:'About Jamie Williams, a computer science student interested in game programming and VR.',body:
 heading('ABOUT', 'Hey, I’m Jamie.', 'I’m a computer science student. I mainly work in Unity and C#, and I’m interested in gameplay programming and VR.') +
 article([['me','About me'],['site','This site'],['contact','Find me']], `<section id="me"><h2>About me</h2><p>I’ve worked on games, VR, interactive controllers, and university programming projects. I’d like to work in game development professionally.</p><p>I’m also interested in learning more Unreal and C++.</p></section><section id="site"><h2>This site</h2><p>This is my personal website. My <a href="${portfolio}">game dev portfolio</a> has more of my project work.</p><p>The <a href="/lab/rfid/">RFID platformer</a> is a game I made for a hackathon. The code and development notes are on GitHub.</p></section><section id="contact"><h2>Find me</h2><div class="contact-links"><a href="${github}">GitHub <span>EyeInDisguise ↗</span></a><a href="${portfolio}">Game dev portfolio <span>jamiegamedev.me ↗</span></a></div></section>`)},
{path:'/notes/',title:'Notes',description:'Notes on Jamie Williams’s personal website. No notes have been posted yet.',body:heading('NOTES','Notes.','No notes here yet.')},
{path:'/now/',title:'Now',description:'Jamie Williams is studying computer science and working with Unity and C#.',body:heading('NOW','What I’m up to.','Studying computer science and working with Unity and C#.') + `<div class="prose"><p>I’m interested in gameplay programming and VR, and learning more Unreal and C++.</p><p><a href="/lab/rfid/">My RFID platformer ↗</a></p></div>`},
{path:'/colophon/',title:'Colophon',description:'Technical details and source code for Jamie Williams’s personal website.',body:
 heading('THIS WEBSITE', 'Colophon.', 'A few details about the site.') +
 article([['build','Code'],['type','Fonts']], `<section id="build"><h2>Code</h2><p>Static HTML and CSS, generated by a small Node.js script. JavaScript handles the RFID selector, the scroll sequence, and the small cursor reticle. No tracking or analytics.</p><p><a href="${repo}">Website source on GitHub ↗</a></p></section><section id="type"><h2>Fonts</h2><p><a href="https://github.com/uswds/public-sans">Public Sans</a> and <a href="https://www.ibm.com/plex/">IBM Plex Mono</a>, hosted locally. The italic heading uses Georgia.</p></section>`)},
{path:'/404/',title:'Page not found',description:'This page could not be found on Jamie Williams’s personal website.',body:heading('404','Page not found.','That page may have moved or been removed.') + `<div class="error-links"><a class="button-link" href="/">Back home →</a><a class="text-link" href="/lab/">Projects →</a></div>`}
];
