import { experiments, notes } from './content.mjs';
import { curve } from './assets/spring-model.js';
import { github, portfolio } from './layout.mjs';
const repo = `${github}/jamiewilliams.website`;
const game = `${github}/Jamie-Hackathon-2026`;
const play = 'https://play.unity.com/en/games/51c4cc8b-b2fc-4f07-a06d-968e66fd5fc3/polished';
const heading = (index, title, text) => `<header class="page-heading"><span class="eyebrow">${index}</span><h1>${title}</h1><p>${text}</p></header>`;
const article = (contents, body) => `<div class="article-layout"><aside class="article-index"><span class="eyebrow">ON THIS PAGE</span><nav aria-label="On this page">${contents.map(([id, title])=>`<a href="#${id}">${title}</a>`).join('')}</nav></aside><article class="prose">${body}</article></div>`;
export const detailPages = [
{ path: '/lab/', title: 'Lab', description: 'Experiments, prototypes, and work in progress. Jamie Williams’s development lab.', body:
  heading('01 / LAB', 'Things in progress.', 'Small experiments and longer-running projects. Some playable, some still being figured out.') +
  `<div class="archive-label"><span>ENTRY / SUBJECT</span><span>TOOLS / STATE</span></div><div class="experiment-list">${experiments.map(e=>`<a class="experiment-row" href="${e.path}"><span class="experiment-id">${e.id}</span><div><h2>${e.title}</h2><p>${e.description}</p></div><div class="experiment-meta"><span>${e.medium}</span><span>${e.status}</span></div><span class="row-arrow" aria-hidden="true">↗</span></a>`).join('')}</div><p class="archive-footnote">The archive starts here. Unity and VR work will get more space as there’s material to share.</p>`
},
{ path: '/lab/spring/', title: 'A little spring in it', description: 'An interactive spring-response study. Adjust damping and compare underdamped, critical, and overdamped motion.', script: '/assets/spring.js', body:
  heading('EXP–001 / JAVASCRIPT + SVG', 'A little spring in it.', 'Change one number. Go from loose and bouncy to slow and deliberate.') +
  `<section class="spring-bench" data-spring aria-label="Interactive spring response"><div class="spring-top"><span class="eyebrow">UNIT STEP RESPONSE</span><span class="eyebrow accent" data-regime>Underdamped</span></div><div class="spring-chart"><svg viewBox="0 0 760 310" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">Spring position over three seconds</title><desc id="chart-desc">The target is 1. A lightly damped spring crosses the target several times before settling. Change the damping ratio below to compare behaviours.</desc><path class="chart-grid" d="M40 50H720 M40 100H720 M40 200H720 M40 250H720 M40 50V250 M267 50V250 M493 50V250 M720 50V250"/><path class="plot-target" d="M40 150H720"/><text x="9" y="254">0</text><text x="9" y="154">1</text><text x="9" y="54">2</text><text x="40" y="282">0 s</text><text x="257" y="282">1 s</text><text x="483" y="282">2 s</text><text x="700" y="282">3 s</text><text x="640" y="140">target = 1</text><path class="plot-line" data-trace d="${curve(.35)}"/><circle class="plot-dot" data-dot cx="40" cy="250" r="7"/></svg></div><div class="spring-controls" data-controls hidden><div class="damping-control"><label for="damping">Damping ratio <span aria-hidden="true">ζ</span></label><output for="damping">0.35</output><input id="damping" type="range" min="0.05" max="2" step="0.05" value="0.35"><div class="range-ends"><span>More bounce</span><span>More resistance</span></div></div><div class="preset-controls"><span class="control-label">COMPARE</span><div class="preset-buttons" role="group" aria-label="Damping presets"><button data-preset="0.35" aria-pressed="true">Bouncy</button><button data-preset="1" aria-pressed="false">Critical</button><button data-preset="1.8" aria-pressed="false">Sluggish</button></div></div></div><div class="spring-actions" data-controls hidden><button class="run-button" data-play>Run response</button><button class="stop-button" data-stop disabled>Stop</button><p class="spring-status" role="status" data-status></p></div><noscript><p class="no-script">This is the response at a damping ratio of 0.35. Enable JavaScript to adjust it; the explanation below works without it.</p></noscript></section>
  ${article([['idea','The idea'],['model','The model'],['limits','What this leaves out']], `<section id="idea"><h2>The idea</h2><p>A spring can make a camera or interface element feel responsive, heavy, or slightly out of control. This study isolates the damping ratio so the difference is easy to see.</p><p>The curve shows the whole response. “Run response” follows that same curve over three seconds. Nothing animates until you ask it to.</p></section><section id="model"><h2>The model</h2><p>The spring starts at position 0, at rest. Its target moves instantly to 1. Natural frequency stays fixed at 9 radians per second; only damping changes.</p><details><summary>Inspect the equation</summary><pre><code>x″ + 2ζωx′ + ω²x = ω²
x(0) = 0, x′(0) = 0
ω = 9 rad/s</code></pre><p>The plot uses the analytic solution, rather than integrating a simulation each frame. Its position therefore doesn’t depend on the display’s refresh rate.</p></details><p><a href="/notes/spring-response/">Read the damping reference →</a></p></section><section id="limits"><h2>What this leaves out</h2><p>This is a one-dimensional, linear spring with a fixed target. It doesn’t model collisions, changing targets, or a real game camera. A three-second window also doesn’t mean every setting has settled.</p><p class="small muted">Built as a web experiment for this site. <a href="${repo}/blob/main/src/assets/spring-model.js">View the model on GitHub ↗</a></p></section>`)}`
},
{ path:'/lab/rfid/', title:'Physical tokens, virtual abilities', description:'Notes on Jamie Williams’s Unity speedrun platformer and RFID ability controller.', body:
 heading('EXP–002 / UNITY + C# + ESP32', 'Physical tokens.<br>Virtual abilities.', 'A 2D speedrun platformer where scanning an RFID token changes the player’s movement abilities.') +
 `<div class="project-facts"><div><span class="eyebrow">ROLE</span><strong>Solo project</strong></div><div><span class="eyebrow">STATE</span><strong>In progress</strong></div><div><span class="eyebrow">ORIGINAL BUILD</span><strong>2–3 days / hackathon</strong></div><div><a class="text-link" href="${play}">Play the Unity build ↗</a></div></div>` +
 article([['trying','The idea'],['problem','The technical bit'],['approach','One input path'],['unfinished','Still rough'],['next','Next passes']], `<section id="trying"><h2>The idea</h2><p>Change one movement rule and a platformer feels different. This project takes that literally: physical tokens select dash, wall jump, gravity flip, or time stop.</p><p>The first version was a solo hackathon build. It uses Unity, an ESP32, and an MFRC522 RFID reader. A regular keyboard works too, so the hardware isn’t required to try it.</p></section><section id="problem"><h2>The technical bit</h2><p>The interesting boundary is between the thing on the desk and the player on screen. Unity needs to receive the ability choice without being coupled to the RFID reader.</p></section><section id="approach"><h2>One input path</h2><div class="signal-flow" aria-label="RFID input path"><span>RFID token</span><b aria-hidden="true">↓</b><span>MFRC522 reader + ESP32</span><b aria-hidden="true">↓</b><span>Bluetooth keyboard input</span><b aria-hidden="true">↓</b><span>Unity ability selection</span></div><p>The ESP32 presents itself as a Bluetooth keyboard. Each recognised token sends a number key. Unity receives ordinary keyboard input, so physical and keyboard controls use the same ability-selection path.</p><p>Movement includes acceleration, coyote time, jump buffering, and variable jump height. A timer, local leaderboard, and ghost replay support the speedrun loop.</p></section><section id="unfinished"><h2>Still rough</h2><p>Crush detection, resets, and race/leaderboard edge cases remain in progress. Movement, level readability, the ability HUD, and the browser experience are also being refined.</p><p>The repository is ahead of some older exported builds. The <a href="${game}">project README</a> explains the build setup and current limitations.</p></section><section id="next"><h2>Next passes</h2><p>The next useful addition here is footage showing a physical token changing the game, alongside a closer look at movement and reset behaviour. There’s no stand-in screenshot for that yet.</p><p><a href="${play}">Play in the browser ↗</a> <span class="link-divider">/</span> <a href="${game}">Read the source and development notes ↗</a></p><p class="small muted">This entry is based on the project’s existing README. The original development notes also document tutorial resources and AI assistance.</p></section>`)
},
{path:'/lab/this-website/',title:'This website',description:'The structure, constraints, and first iteration of Jamie Williams’s personal website.',body:
 heading('SITE–001 / FIRST EDITION', 'A place to keep things.', 'The site itself is a small project: a notebook, a lab, and somewhere to put work that doesn’t need to be a finished portfolio piece.') +
 article([['purpose','The job'],['approach','The approach'],['tradeoff','The trade-off'],['next','What comes next']], `<section id="purpose"><h2>The job</h2><p>The <a href="${portfolio}">game-development portfolio</a> has a clear job: present selected work. This site gives experiments and smaller notes a home of their own.</p></section><section id="approach"><h2>The approach</h2><p>Static HTML keeps every page readable without JavaScript. A shared layout and a small build script keep the navigation, content, and page metadata consistent.</p><p>The spring study adds a little play to the lab. Its graph is also an actual artifact for the homepage, instead of a decorative background.</p></section><section id="tradeoff"><h2>The trade-off</h2><p>A small custom build is easy to inspect, but it doesn’t come with an editor or a large publishing system. For this amount of content, that’s a reasonable constraint. If writing grows, Markdown is the first thing to add.</p><p>There are no substitute project screenshots. The archive stays short until there’s real material to put in it.</p></section><section id="next"><h2>What comes next</h2><p>More notes from actual projects, footage from the RFID controller, and a fuller record of changes as the site develops.</p><p><a href="/colophon/">The technical colophon →</a> <span class="link-divider">/</span> <a href="${repo}">Source ↗</a></p></section>`)
},
{path:'/notes/',title:'Notes',description:'Short references and longer technical notes. A development notebook by Jamie Williams.',body:
 heading('02 / NOTEBOOK', 'Worth writing down.', 'Short references, working explanations, and room for longer technical notes.') +
 `<div class="notes-archive">${notes.map(n=>`<a class="note-row" href="${n.path}"><time class="note-date" datetime="${n.date}">${n.displayDate}</time><h2>${n.title}</h2><p>${n.description}</p><span class="note-type">${n.tag}<span aria-hidden="true">↗</span></span></a>`).join('')}</div><p class="archive-footnote">The notebook is just getting started.</p>`
},
{path:'/notes/spring-response/',title:'What the damping ratio changes',description:'A concise reference for underdamped, critically damped, and overdamped spring responses.',body:
 heading('REFERENCE / MOTION / 22 SEP 2026', 'What the damping<br>ratio changes.', 'Three behaviours, one equation. A companion to the spring experiment.') +
 article([['damping','A useful distinction'],['regimes','Three regimes'],['game','In a game'],['equation','The equation']], `<section id="damping"><h2>A useful distinction</h2><p>Stiffness and damping do different jobs. Stiffness pulls the spring towards its target. Damping resists velocity and removes energy from the motion.</p><p>The damping ratio, ζ, describes damping relative to the critical amount. In this experiment the mass and natural frequency stay fixed, so changing ζ isolates one behaviour.</p></section><section id="regimes"><h2>Three regimes</h2><dl class="definition-list"><dt>ζ &lt; 1 / Underdamped</dt><dd>The response overshoots the target and oscillates around it. Less damping means more persistent oscillation.</dd><dt>ζ = 1 / Critically damped</dt><dd>The fastest return without oscillation for this linear spring starting at rest after a step in the target.</dd><dt>ζ &gt; 1 / Overdamped</dt><dd>No oscillation, but a slower approach. Increasing damping further makes the response more sluggish.</dd></dl><p><a href="/lab/spring/">Compare all three in the lab →</a></p></section><section id="game"><h2>In a game</h2><p>For a camera, a little overshoot can be expressive. For a small interface adjustment, the same overshoot might make the control feel imprecise. The right behaviour depends on what the player needs to follow.</p><p>A graph helps compare settings, but it can’t tell you how a moving target, collision, or camera transition will feel in context. That still needs testing in the actual scene.</p></section><section id="equation"><h2>The equation</h2><pre><code>x″ + 2ζωx′ + ω²x = ω² · target</code></pre><p>Here x is position, x′ is velocity, x″ is acceleration, and ω is natural frequency. This version sets mass to one. The lab uses an exact solution for a fixed target step, rather than an approximate frame-by-frame simulation.</p><p class="small muted">Reference: <a href="https://phys.libretexts.org/Bookshelves/University_Physics/University_Physics_(OpenStax)/Book%3A_University_Physics_I_-_Mechanics_Sound_Oscillations_and_Waves_(OpenStax)/15%3A_Oscillations/15.06%3A_Damped_Oscillations">OpenStax — Damped Oscillations</a>. The interactive model is in <a href="${repo}/blob/main/src/assets/spring-model.js">spring-model.js</a>.</p></section>`)
},
{path:'/now/',title:'Now',description:'What Jamie Williams is building and learning. Updated September 2026.',body:
 heading('03 / NOW / SEPTEMBER 2026', 'Mostly Unity.<br>Still curious.', 'A small snapshot of what has my attention.') +
 `<div class="now-list"><section><span class="eyebrow">BUILDING</span><div><h2>Gameplay, one system at a time.</h2><p>Working with Unity and C#, with an interest in player movement, gameplay behaviour, and interactive controllers. The <a href="/lab/rfid/">RFID platformer</a> is one ongoing project.</p></div></section><section><span class="eyebrow">LEARNING</span><div><h2>More of the machinery underneath.</h2><p>Computer science, systems, and the programming behind games. Unreal and C++ are directions I want to explore further as I improve.</p></div></section><section><span class="eyebrow">EXPERIMENTING</span><div><h2>Different ways to interact.</h2><p>VR, game mechanics, and the boundary between a physical controller and what happens on screen. Also, giving small web experiments somewhere to live.</p></div></section><section><span class="eyebrow">ON THE HORIZON</span><div><h2>Making games professionally.</h2><p>Game development is the direction I’m working towards. Longer term, I’m also interested in opportunities at studios in Japan.</p></div></section></div><p class="archive-footnote">A dated snapshot, not a live status indicator.</p>`
},
{path:'/about/',title:'About',description:'Jamie Williams is a computer science student interested in gameplay programming, Unity, C#, VR, and interactive experiments.',body:
 heading('04 / ABOUT', 'Jamie Williams.', 'Computer science student. Aspiring game developer. Interested in how things work, and what happens when you change them.') +
 article([['work','What I work with'],['here','What goes here'],['contact','Find me']], `<section id="work"><h2>What I work with</h2><p>Most of my current work is in Unity and C#. I’ve worked with VR, gameplay systems, interactive controllers, and university programming projects. Game programming is the direction I want to pursue professionally.</p><p>I’m particularly interested in the parts a player can feel: movement, behaviour, interaction, and the systems holding those together.</p></section><section id="here"><h2>What goes here</h2><p>This is the place for work in progress, smaller experiments, and notes that might be useful later. It can stay a little unfinished.</p><p>For selected projects and a more direct view of my game-development work, visit <a href="${portfolio}">my portfolio ↗</a>.</p></section><section id="contact"><h2>Find me</h2><p>You can find my code on GitHub and selected game-development work on my portfolio.</p><div class="contact-links"><a href="${github}">GitHub <span>@EyeInDisguise ↗</span></a><a href="${portfolio}">Game-development portfolio <span>jamiegamedev.me ↗</span></a></div></section>`)
},
{path:'/colophon/',title:'Colophon',description:'How this website is built: static HTML, a small Node.js build, locally hosted type, and a restrained interactive spring study.',body:
 heading('SITE NOTES / FIRST EDITION', 'Colophon.', 'A few notes about the thing you’re reading this on.') +
 article([['design','Design'],['type','Type'],['build','Build'],['access','Access & motion'],['history','Iterations']], `<section id="design"><h2>Design</h2><p>A field notebook with a little of a game engine’s inspection view. The dark olive background relates to the warm paper and olive palette of my portfolio. Fine rules and numbered entries do most of the organising.</p><p>The lab has space to show an experiment. Notes use a quieter reading layout. The two don’t need to look like the same set of cards.</p></section><section id="type"><h2>Type</h2><p><a href="https://github.com/uswds/public-sans">Public Sans</a> handles headings and reading text. <a href="https://www.ibm.com/plex/">IBM Plex Mono</a> is used for dates, entry numbers, and small technical annotations. Both are open-source fonts, served from this site as WOFF2 files. The italic on the homepage uses Georgia from the device’s system fonts.</p></section><section id="build"><h2>Build</h2><p>A small Node.js script renders shared templates into complete HTML pages. There’s no framework runtime, database, or client-side router. The spring experiment is an isolated JavaScript module; the rest is HTML and CSS.</p><p>Its graph uses the analytic solution for a damped spring. The same function draws the static curve and moves the interactive marker.</p><p><a href="${repo}">The source is on GitHub ↗</a></p></section><section id="access"><h2>Access & motion</h2><p>All writing and navigation work without JavaScript. The experiment includes a static diagram and explanation as its fallback. Keyboard focus is visible, controls use native buttons and inputs, and the mobile navigation stays in view without a menu toggle.</p><p>Motion starts only when requested. With reduced motion enabled, the experiment shows its final position immediately. Fonts are hosted locally, and this site doesn’t add analytics, tracking cookies, or third-party embeds.</p></section><section id="history"><h2>Iterations</h2><p><time datetime="2026-09-22">September 2026</time> — first edition of the notebook and lab, with the spring response study and an entry on the RFID platformer.</p></section>`)
},
{path:'/404/',title:'Page not found',description:'This page is missing. Return to Jamie Williams’s notebook or development lab.',body:
 heading('404 / MISSING PAGE', 'Not in this notebook.', 'That page may have moved, or the address may be slightly off.') + `<div class="error-links"><a class="button-link" href="/">Back to the homepage →</a><a class="text-link" href="/lab/">Try the lab →</a></div>`
}
];
