import { github, portfolio } from './layout.mjs';
import { abilitySelector } from './ability-selector.mjs';

const repo = `${github}/jamiewilliams.website`;
const game = `${github}/Jamie-Hackathon-2026`;
const play = 'https://play.unity.com/en/games/51c4cc8b-b2fc-4f07-a06d-968e66fd5fc3/polished';
const heading = (number, label, title, text) => `<header class="folio-heading"><div class="section-kicker"><span>${number} / ${label}</span><span>JAMIE WILLIAMS</span></div><h1>${title}</h1><p>${text}</p></header>`;
const article = (contents, body) => `<div class="article-layout"><aside class="article-index"><span class="eyebrow">ON THIS PAGE</span><nav aria-label="On this page">${contents.map(([id, title])=>`<a href="#${id}">${title}</a>`).join('')}</nav></aside><article class="prose">${body}</article></div>`;

export const detailPages = [
  { path: '/lab/', title: 'Lab', description: 'Jamie Williams’s experiments and projects, including a Unity game controlled with physical RFID tokens.', body:
    heading('01', 'LAB', 'The lab.', 'Things I’ve made and things I’m still figuring out.') +
    `<div class="lab-intro"><p>I’m keeping experiments, prototypes, and longer project notes here. The <a href="${portfolio}">game dev portfolio ↗</a> has an overview of my game projects.</p><span class="folio-stamp" aria-hidden="true">JW<br>01</span></div>
    <a class="lab-entry" href="/lab/rfid/"><span class="lab-entry-no">ENTRY 001 / UNITY · C# · HARDWARE</span><span class="lab-entry-title">RFID<br>platformer<span aria-hidden="true">↗</span></span><span class="lab-entry-description">A platformer where physical tokens change your abilities. Made for a hackathon; still being worked on.</span></a><p class="archive-footnote">That’s the one documented here so far. More work is on <a href="${portfolio}">the game portfolio</a> and <a href="${github}">GitHub</a>.</p>` },
  { path: '/lab/rfid/', title: 'RFID platformer', description: 'A Unity platformer Jamie Williams made for a hackathon, with an ESP32 RFID controller.', body:
    heading('01.1', 'LAB / GAME', 'RFID platformer.', 'I made this for a hackathon. Scan a physical token and the game switches your ability.') +
    `<div class="project-facts"><div><span>WHAT IT IS</span><strong>2D speedrun platformer</strong></div><div><span>BUILT WITH</span><strong>Unity, C#, ESP32, RFID</strong></div><div><span>FIRST VERSION</span><strong>2–3 days</strong></div></div><div class="project-tools"><a href="${play}">Play the game ↗</a><a href="${game}">Source and dev notes ↗</a></div><div class="project-ability">${abilitySelector()}</div>` +
    article([['game','The game'],['controller','The controller'],['rough','Still rough'],['links','Links']], `<section id="game"><h2>The game</h2><p>It’s a 2D speedrun platformer with four abilities: dash, wall jump, gravity flip, and time stop. You can switch between them using RFID tokens or a regular keyboard.</p><p>The movement has acceleration, coyote time, jump buffering, and variable jump height. There’s also a timer, a local leaderboard, and a ghost replay.</p></section><section id="controller"><h2>The controller</h2><p>An MFRC522 reader scans the tokens. The ESP32 sends a number key over Bluetooth, and Unity uses that key to select an ability.</p><div class="signal-flow" aria-label="Controller input path"><span>RFID token</span><b aria-hidden="true">↓</b><span>MFRC522 + ESP32</span><b aria-hidden="true">↓</b><span>Bluetooth key</span><b aria-hidden="true">↓</b><span>Unity</span></div><p>The ESP32 acts as a keyboard, so the game doesn’t need a separate input system for the hardware.</p></section><section id="rough"><h2>Still rough</h2><p>Crush detection, resets, and some race and leaderboard edge cases still need work. The repository has more recent changes than some exported builds; the README has the current development notes.</p></section><section id="links"><h2>Try it</h2><p><a href="${play}">Play the browser build ↗</a></p><p><a href="${game}">Source code and dev notes ↗</a></p></section>`) },
  { path: '/about/', title: 'About', description: 'About Jamie Williams, a computer science student interested in gameplay programming, VR, and the games he loves.', body:
    heading('02', 'ABOUT', 'About me.', 'I’m Jamie. I study computer science at UQ and spend a lot of my time making games.') +
    article([['work','What I do'],['games','Games'],['contact','Find me']], `<section id="work"><h2>What I do</h2><p>Most of my work so far has been in Unity and C#. I like gameplay systems, movement, physical inputs, and VR. I’m learning more Unreal and C++ as I go.</p><p>This is my personal site. <a href="${portfolio}">My game development portfolio</a> is where the more formal project work lives.</p></section><section id="games"><h2>Games I love</h2><p>The House in Fata Morgana, NieR, Elden Ring, and Monster Hunter. I like stories that stay with you and games that make you want to keep looking around.</p></section><section id="contact"><h2>Find me</h2><div class="contact-links"><a href="${github}">GitHub <span>EyeInDisguise ↗</span></a><a href="${portfolio}">Game dev portfolio <span>jamiegamedev.me ↗</span></a></div></section>`) },
  { path: '/notes/', title: 'Notes', description: 'Jamie Williams’s personal notes page. Nothing has been published here yet.', body:
    heading('03', 'NOTES', 'Notes.', 'Nothing published here yet.') + `<div class="empty-page"><span class="empty-mark" aria-hidden="true">✳</span><p>I’ll put write-ups here when I have something worth keeping. Until then, <a href="/lab/">the lab</a> has the work I can show.</p></div>` },
  { path: '/now/', title: 'Now', description: 'What Jamie Williams is studying and working on as of September 2026.', body:
    heading('04', 'NOW', 'Right now.', 'September 2026') + `<div class="now-list"><div><span>01 / STUDYING</span><p>Computer science at UQ.</p></div><div><span>02 / MAKING</span><p>Games in Unity and C#. I’m especially interested in how movement and input feel.</p></div><div><span>03 / LEARNING</span><p>More Unreal and C++, alongside the usual things that come up while making games.</p></div></div><p class="archive-footnote"><a href="${portfolio}">See my game dev work ↗</a></p>` },
  { path: '/colophon/', title: 'Colophon', description: 'How Jamie Williams’s personal website was designed and built.', body:
    heading('05', 'COLOPHON', 'Colophon.', 'A few notes on how this site is put together.') +
    article([['idea','The idea'],['build','Code'],['type','Type'],['interaction','Interaction']], `<section id="idea"><h2>The idea</h2><p>I wanted a personal site that felt separate from my game development portfolio. This one is closer to an index or field notebook. The dark rooms, warm paper, and little details come from games and stories I like, but the content is just my actual work and interests.</p></section><section id="build"><h2>Code</h2><p>Static HTML generated with a small Node.js script. CSS does most of the visual work. JavaScript handles the scroll scene, cursor, the RFID ability selector, and a couple of hidden things. No tracking or analytics.</p><p><a href="${repo}">Website source on GitHub ↗</a><button class="bonus-mark" type="button" data-open-bonus aria-label="Open hidden bonus room" title="???">◇</button></p></section><section id="type"><h2>Type</h2><p><a href="https://github.com/CatharsisFonts/Cormorant">Cormorant Garamond</a> gives the big headings their shape. <a href="https://www.ibm.com/plex/">IBM Plex Mono</a> handles the small labels. Both are hosted here with their licences.</p></section><section id="interaction"><h2>Interaction</h2><p>The first scene opens as you scroll. It doesn’t change how the page scrolls, and it stays still if you prefer reduced motion. The rest of the site uses normal links and works without JavaScript.</p></section>`) },
  { path: '/404/', title: 'Page not found', description: 'This page could not be found on Jamie Williams’s personal website.', body:
    heading('404', 'LOST', 'Wrong door.', 'That page may have moved or been removed.') + `<div class="error-links"><a href="/">Back to the index ↗</a><a href="/lab/">Try the lab ↗</a></div>` },
];
