import { curve } from './assets/spring-model.js';
import { detailPages } from './detail-pages.mjs';
export const pages = [{
  path: '/', title: 'Notebook & lab', description: 'Jamie Williams’s projects, experiments, and programming notes.',
  body: `<section class="intro"><div class="eyebrow"><span class="tiny-cross" aria-hidden="true">+</span> PERSONAL WEBSITE <span class="edition">NOTEBOOK / 001</span></div>
  <div class="intro-grid"><h1>Jamie<br><em>Williams.</em></h1><div class="intro-copy"><p>I’m a computer science student working mainly with Unity and C#. I’m interested in gameplay programming and VR.</p><p class="muted">I use this site for projects, experiments, and notes.</p><a class="text-link" href="/about/">About me <span aria-hidden="true">↗</span></a></div></div></section>
  <section class="lab-feature" aria-labelledby="lab-heading"><div class="section-heading"><h2 id="lab-heading"><span class="section-index">01 /</span> On the workbench</h2><a href="/lab/">Open the lab <span aria-hidden="true">↗</span></a></div>
  <div class="bench"><div class="bench-info"><span class="eyebrow accent">EXP–001 / WEB EXPERIMENT</span><h3>Spring <br>response</h3><p>Adjust the damping to see how a spring moves towards its target.</p><a class="button-link" href="/lab/spring/">Play with the spring <span aria-hidden="true">↗</span></a><div class="bench-note"><span class="status-mark" aria-hidden="true"></span> Interactive study <span class="muted">/ built for this site</span></div></div><a class="plot-preview" href="/lab/spring/" aria-label="Open the interactive spring experiment"><div class="plot-meta"><span>SPRING RESPONSE</span><span>ζ = 0.35</span></div><svg viewBox="0 0 760 310" role="img" aria-label="An underdamped spring overshoots its target and settles"><path class="plot-target" d="M40 100H720"/><path class="plot-line" transform="translate(0,-125) scale(1,1.5)" d="${curve(.35)}"/><circle class="plot-dot" cx="124.46" cy="53.62" r="6"/><path class="plot-annotation" d="M132 48L168 28H255"/><text x="170" y="20">the overshoot</text><text x="650" y="89">target</text><text x="40" y="290">0 s</text><text x="680" y="290">3 s</text></svg><div class="plot-caption"><span>DAMPING: 0.35 / DURATION: 3 s</span><span aria-hidden="true">↗</span></div></a></div><a class="workbench-extra" href="/lab/rfid/"><span class="eyebrow">ALSO ON THE BENCH</span><span>Physical tokens, virtual abilities</span><span class="muted">Unity / RFID</span><span aria-hidden="true">↗</span></a></section>
  <section class="home-bottom"><div><div class="section-heading"><h2><span class="section-index">02 /</span> Field notes</h2><a href="/notes/">All notes ↗</a></div><a class="note-row" href="/notes/spring-response/"><span class="note-date">22 SEP 2026</span><h3>What the damping ratio changes</h3><span class="note-type">A small technical reference <span aria-hidden="true">↗</span></span></a><a class="note-row" href="/colophon/"><span class="note-date">SITE NOTES</span><h3>How this site is built</h3><span class="note-type">Colophon & implementation <span aria-hidden="true">↗</span></span></a></div><aside class="now-aside"><span class="eyebrow">CURRENTLY</span><h2>What I’m<br>working on.</h2><p>Working with C#, exploring gameplay systems and VR, and looking towards Unreal and C++.</p><a class="text-link" href="/now/">What I’m up to <span aria-hidden="true">↗</span></a></aside></section>`
}];

pages.push(...detailPages);
